# Generated by Django 4.2.1 on 2023-05-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2000-10-21'),
            preserve_default=False,
        ),
    ]
